# Generated by Django 2.2 on 2020-11-07 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CdtBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_brand_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CdtCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_category_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CdtColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CdtSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_name_size', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='CdtSubcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_subcategory_name', models.CharField(max_length=50)),
                ('id_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.CdtCategory')),
            ],
        ),
        migrations.CreateModel(
            name='CdtVendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_name_vendor', models.CharField(max_length=50)),
                ('nm_phone_number_vendor', models.CharField(max_length=10)),
                ('tx_description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TdtProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_product_name', models.CharField(max_length=75)),
                ('tx_description', models.CharField(max_length=75)),
                ('gender', models.CharField(choices=[('0', 'male'), ('1', 'female'), ('2', 'others')], max_length=2)),
                ('nm_sale_unit', models.DecimalField(decimal_places=2, max_digits=8)),
                ('id_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.CdtBrand')),
                ('id_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.CdtColor')),
                ('id_subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.CdtSubcategory')),
                ('id_vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.CdtVendor')),
                ('size', models.ManyToManyField(to='store.CdtSize')),
            ],
        ),
        migrations.CreateModel(
            name='CdtProductPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_url_photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('bl_primary', models.BooleanField(default=False)),
                ('id_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.TdtProduct')),
            ],
        ),
    ]
