# Generated by Django 2.2 on 2020-11-07 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tdtproduct',
            name='id_color',
        ),
        migrations.AddField(
            model_name='tdtproduct',
            name='id_color',
            field=models.ManyToManyField(to='store.CdtColor'),
        ),
    ]
