# Generated by Django 2.2 on 2020-11-07 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20201107_1547'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cdtcolor',
            old_name='color',
            new_name='tx_name_color',
        ),
    ]
