# Generated by Django 2.2 on 2020-11-09 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20201108_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='tdtproduct',
            name='img_photo1',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='tdtproduct',
            name='img_photo2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='tdtproduct',
            name='img_photo3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.RemoveField(
            model_name='tdtproduct',
            name='size',
        ),
        migrations.AddField(
            model_name='tdtproduct',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.CdtSize'),
        ),
        migrations.DeleteModel(
            name='CdtProductPhoto',
        ),
    ]
