# Generated by Django 2.2 on 2020-11-11 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20201109_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cdtvendor',
            name='nm_phone_number_vendor',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
