# Generated by Django 2.2 on 2020-11-21 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20201121_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cdtcolor',
            name='id_product',
        ),
        migrations.AddField(
            model_name='tdtproduct',
            name='id_color',
            field=models.ManyToManyField(to='store.CdtColor'),
        ),
        migrations.AlterField(
            model_name='cdtsubcategory',
            name='tx_subcategory_name',
            field=models.CharField(max_length=50, verbose_name='Subcategory'),
        ),
        migrations.AlterField(
            model_name='cdtvendor',
            name='nm_phone_number_vendor',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='cdtvendor',
            name='tx_description',
            field=models.CharField(max_length=50, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='cdtvendor',
            name='tx_name_vendor',
            field=models.CharField(max_length=50, verbose_name='Vendor'),
        ),
        migrations.DeleteModel(
            name='CdtProductPhoto',
        ),
    ]
