# Generated by Django 2.2 on 2020-11-22 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20201122_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tdtproduct',
            name='tx_description',
            field=models.TextField(max_length=300, verbose_name='Description'),
        ),
    ]
