# Generated by Django 2.2 on 2020-11-22 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20201122_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cdtproductphoto',
            name='id_color',
        ),
        migrations.DeleteModel(
            name='CdtSize',
        ),
        migrations.RemoveField(
            model_name='cdtcolor',
            name='id_product',
        ),
        migrations.AddField(
            model_name='tdtproduct',
            name='id_color',
            field=models.ManyToManyField(to='store.CdtColor'),
        ),
        migrations.AlterField(
            model_name='cdtcolor',
            name='tx_name_color',
            field=models.CharField(max_length=50, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='tdtproduct',
            name='tx_description',
            field=models.CharField(max_length=75, verbose_name='Description'),
        ),
        migrations.DeleteModel(
            name='CdtProductPhoto',
        ),
    ]
