# Generated by Django 2.2 on 2020-11-22 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20201122_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='CdtSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_name_size', models.CharField(max_length=4)),
            ],
            options={
                'verbose_name': 'Size',
                'verbose_name_plural': 'Sizes',
            },
        ),
        migrations.RemoveField(
            model_name='tdtproduct',
            name='id_color',
        ),
        migrations.AddField(
            model_name='cdtcolor',
            name='id_product',
            field=models.ForeignKey(default=35, on_delete=django.db.models.deletion.CASCADE, to='store.TdtProduct'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cdtcolor',
            name='tx_name_color',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tdtproduct',
            name='tx_description',
            field=models.TextField(max_length=300, verbose_name='Description'),
        ),
        migrations.CreateModel(
            name='CdtProductPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_url_photo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Photo')),
                ('bl_primary', models.BooleanField(default=False, verbose_name='Primary')),
                ('id_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.CdtColor')),
            ],
            options={
                'verbose_name': 'Photo',
                'verbose_name_plural': 'Photos',
            },
        ),
    ]
