# Generated by Django 2.2 on 2020-11-22 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20201122_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cdtcolor',
            name='id_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_product', to='store.TdtProduct'),
        ),
    ]
