# Generated by Django 2.2 on 2020-11-23 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20201122_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cdtcolor',
            name='id_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tdtproduct_cdtcolor', to='store.TdtProduct'),
        ),
    ]
