# Generated by Django 2.2 on 2020-11-28 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_auto_20201123_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cdtcolor',
            name='id_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.TdtProduct'),
        ),
    ]
