# Generated by Django 2.2 on 2020-11-29 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_auto_20201128_2058'),
    ]

    operations = [
        migrations.CreateModel(
            name='CdtCategoryPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_category_person', models.CharField(max_length=50, verbose_name='Category Person')),
            ],
        ),
        migrations.RemoveField(
            model_name='tdtproduct',
            name='gender',
        ),
        migrations.AddField(
            model_name='tdtproduct',
            name='id_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.CdtCategory'),
        ),
        migrations.AddField(
            model_name='cdtcategory',
            name='id_category_person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.CdtCategoryPerson'),
        ),
        migrations.AddField(
            model_name='tdtproduct',
            name='id_category_person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.CdtCategoryPerson'),
        ),
    ]
