# Generated by Django 2.2 on 2020-11-29 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_auto_20201129_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cdtcolor',
            name='id_product',
        ),
        migrations.AddField(
            model_name='tdtproduct',
            name='id_color',
            field=models.ManyToManyField(to='store.CdtColor'),
        ),
    ]
