# Generated by Django 2.2 on 2020-11-29 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_auto_20201129_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cdtproductphoto',
            name='id_color',
        ),
        migrations.AddField(
            model_name='tdtproduct',
            name='id_photo',
            field=models.ManyToManyField(to='store.CdtProductPhoto'),
        ),
    ]
