# Generated by Django 2.2 on 2020-11-29 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_auto_20201129_1735'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CdtSize',
        ),
    ]
