# Generated by Django 2.2 on 2020-11-29 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_cdtsize_tdtskuproduct'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cdtcategoryperson',
            options={'verbose_name': 'Category Person', 'verbose_name_plural': 'Categories Persons'},
        ),
    ]
