# Generated by Django 2.2 on 2020-11-29 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_auto_20201129_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='cdtsize',
            name='id_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='store.CdtCategory'),
        ),
    ]
