# Generated by Django 2.2 on 2020-12-01 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_cdtsize_id_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cdtvendor',
            name='tx_description',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Description'),
        ),
    ]
