# Generated by Django 2.2 on 2020-11-21 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20201111_0103'),
    ]

    operations = [
        migrations.CreateModel(
            name='CdtProductPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_url_photo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Photo')),
                ('bl_primary', models.BooleanField(default=False, verbose_name='Primary')),
            ],
            options={
                'verbose_name': 'Photo',
                'verbose_name_plural': 'Photos',
            },
        ),
        migrations.RemoveField(
            model_name='tdtproduct',
            name='color',
        ),
        migrations.RemoveField(
            model_name='tdtproduct',
            name='img_photo1',
        ),
        migrations.RemoveField(
            model_name='tdtproduct',
            name='img_photo2',
        ),
        migrations.RemoveField(
            model_name='tdtproduct',
            name='img_photo3',
        ),
        migrations.RemoveField(
            model_name='tdtproduct',
            name='nm_sale_unit',
        ),
        migrations.RemoveField(
            model_name='tdtproduct',
            name='size',
        ),
        migrations.AddField(
            model_name='cdtcolor',
            name='id_product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.TdtProduct'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cdtcolor',
            name='tx_name_color',
            field=models.CharField(max_length=50, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='tdtproduct',
            name='gender',
            field=models.CharField(choices=[('0', 'Gender'), ('1', 'Male'), ('2', 'Female'), ('3', 'Other')], default='0', max_length=2, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='tdtproduct',
            name='tx_description',
            field=models.CharField(max_length=75, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='tdtproduct',
            name='tx_product_name',
            field=models.CharField(max_length=75, verbose_name='Product Name'),
        ),
        migrations.DeleteModel(
            name='CdtSize',
        ),
        migrations.AddField(
            model_name='cdtproductphoto',
            name='id_color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.CdtColor'),
        ),
    ]
